
// This file has been generated by the GUI designer. Do not modify.
namespace SinticBolivia
{
	public partial class SBDatePicker
	{
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Entry entryDate;
		
		private global::Gtk.Button buttonShowCalendar;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SinticBolivia.SBDatePicker
			global::Stetic.BinContainer.Attach (this);
			this.WidthRequest = 198;
			this.Name = "SinticBolivia.SBDatePicker";
			// Container child SinticBolivia.SBDatePicker.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.WidthRequest = 0;
			this.fixed1.HeightRequest = 29;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entryDate = new global::Gtk.Entry ();
			this.entryDate.CanFocus = true;
			this.entryDate.Name = "entryDate";
			this.entryDate.IsEditable = true;
			this.entryDate.InvisibleChar = '●';
			this.fixed1.Add (this.entryDate);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryDate]));
			w1.X = 3;
			w1.Y = 3;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.buttonShowCalendar = new global::Gtk.Button ();
			this.buttonShowCalendar.CanFocus = true;
			this.buttonShowCalendar.Name = "buttonShowCalendar";
			this.buttonShowCalendar.UseUnderline = true;
			this.buttonShowCalendar.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w2 = new global::Gtk.Image ();
			w2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SinticBolivia.datebox_arrow.png");
			this.buttonShowCalendar.Image = w2;
			this.fixed1.Add (this.buttonShowCalendar);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.buttonShowCalendar]));
			w3.X = 163;
			w3.Y = 1;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
